export const COUNTRIES = [
  { code:"AU", name:"Australia", flag:"🇦🇺", lat:-33.87, lng:151.21, risk:"LOW", color:"#00c878", riskScore:12,
    positions:["PSG $180k/wk","Hilts Group","Lot 227 Austral","XRP $19k AUD","Wedding planning"],
    watch:["STC rebate scheme","AUD/USD","NAB rate decisions","Solar policy"] },
  { code:"TZ", name:"Tanzania", flag:"🇹🇿", lat:-5.4, lng:38.9, risk:"MEDIUM", color:"#e8a800", riskScore:58,
    positions:["Pangani 6 acres $175k USD — DD active","Eden Law Chambers engaged","ZIPA 99yr leasehold"],
    watch:["TZS/USD","East Africa conflict","Tanzania elections","ZIPA laws"] },
  { code:"AE", name:"UAE/Dubai", flag:"🇦🇪", lat:25.20, lng:55.27, risk:"LOW", color:"#00c878", riskScore:18,
    positions:["IFZA FZCO registration","Golf Acres Emaar South Apr 2026","Golf Vale Jun 2026","Investor visa Sam + Harrison"],
    watch:["Dubai property index","IFZA fees","AED/AUD","Emaar launch phases"] },
  { code:"ZZ", name:"Zanzibar", flag:"🌍", lat:-6.16, lng:39.19, risk:"MEDIUM", color:"#e8a800", riskScore:52,
    positions:["$100M resort anchor","Matemwe/Paje beachfront","Africa Luxury Properties agent"],
    watch:["Tourism growth","Foreign land laws","East Africa conflict spillover"] },
  { code:"CY", name:"Cyprus", flag:"🇨🇾", lat:35.12, lng:33.43, risk:"LOW", color:"#00c878", riskScore:8,
    positions:["Heritage — Greek Cypriot Australian","Kefalos wedding venue — active thread"],
    watch:["EU stability","Euro zone","Cyprus property"] },
  { code:"TH", name:"Thailand", flag:"🇹🇭", lat:15.87, lng:100.99, risk:"LOW", color:"#0096d4", riskScore:10,
    positions:["Banyan Tree Phuket — Mar 18-21 2026 (closed)","Grande Centre Point Bangkok"],
    watch:["Trip closed — returned Sydney 22 Mar 2026"] },
];
