# AUTO-GENERATED: the 500-feature catalog as data. Do not hand-edit.
CATEGORIES = {
    'A': 'Temporal / Node / Graph Intelligence',
    'B': 'Knowledge Graph Systems',
    'C': 'Discovery Mechanics',
    'D': 'Reality / Simulation Depth',
    'E': 'Instruments / Measurement',
    'F': 'Experiment / Lab Systems',
    'G': 'Self-Driving Lab Features',
    'H': 'Patent Intelligence',
    'I': 'Invention / Technology Transfer',
    'J': 'Materials Science',
    'K': 'Manufacturing / Process Capability',
    'L': 'Supply Chain / Resources',
    'M': 'Physics / Multiphysics',
    'N': 'Electricity / Electronics / Semiconductors',
    'O': 'Photonics / Optical Computing',
    'P': 'Quantum Systems',
    'Q': 'Exotic Quantum / Time-Crystal Systems',
    'R': 'Biology / Genetics Core',
    'S': 'Protein / Molecular Biology',
    'T': 'Disease / Cure Discovery',
    'U': 'Synthetic Biology / Bioengineering',
    'V': 'AI / Foundation Models',
    'W': 'Agent Research Teams',
    'X': 'Society / Institutions / Education',
    'Y': 'App Console / UX / Meta Systems',
}
FEATURES = [
    {'id': 1, 'category': 'A', 'name': 'Temporal knowledge nodes'},
    {'id': 2, 'category': 'A', 'name': 'Cluster knowledge nodes'},
    {'id': 3, 'category': 'A', 'name': 'Causal mechanism nodes'},
    {'id': 4, 'category': 'A', 'name': 'Counterfactual fork nodes'},
    {'id': 5, 'category': 'A', 'name': 'Anomaly trigger nodes'},
    {'id': 6, 'category': 'A', 'name': 'Discovery lineage nodes'},
    {'id': 7, 'category': 'A', 'name': 'Theory version nodes'},
    {'id': 8, 'category': 'A', 'name': 'Evidence chain nodes'},
    {'id': 9, 'category': 'A', 'name': 'Forgotten knowledge nodes'},
    {'id': 10, 'category': 'A', 'name': 'Lost technology nodes'},
    {'id': 11, 'category': 'A', 'name': 'Rediscovery path nodes'},
    {'id': 12, 'category': 'A', 'name': 'Temporal patent nodes'},
    {'id': 13, 'category': 'A', 'name': 'Temporal disease nodes'},
    {'id': 14, 'category': 'A', 'name': 'Temporal material nodes'},
    {'id': 15, 'category': 'A', 'name': 'Temporal civilisation nodes'},
    {'id': 16, 'category': 'A', 'name': 'Research-frontier nodes'},
    {'id': 17, 'category': 'A', 'name': 'Scientific dispute nodes'},
    {'id': 18, 'category': 'A', 'name': 'Obsolete theory nodes'},
    {'id': 19, 'category': 'A', 'name': 'Competing theory clusters'},
    {'id': 20, 'category': 'A', 'name': 'Open-question nodes'},
    {'id': 21, 'category': 'B', 'name': 'Civilisation knowledge graph'},
    {'id': 22, 'category': 'B', 'name': 'Patent knowledge graph'},
    {'id': 23, 'category': 'B', 'name': 'Experiment knowledge graph'},
    {'id': 24, 'category': 'B', 'name': 'Material knowledge graph'},
    {'id': 25, 'category': 'B', 'name': 'Biology knowledge graph'},
    {'id': 26, 'category': 'B', 'name': 'Quantum knowledge graph'},
    {'id': 27, 'category': 'B', 'name': 'Photonic knowledge graph'},
    {'id': 28, 'category': 'B', 'name': 'Instrument knowledge graph'},
    {'id': 29, 'category': 'B', 'name': 'Institution knowledge graph'},
    {'id': 30, 'category': 'B', 'name': 'Manufacturing knowledge graph'},
    {'id': 31, 'category': 'B', 'name': 'Failure-mode graph'},
    {'id': 32, 'category': 'B', 'name': 'Standards graph'},
    {'id': 33, 'category': 'B', 'name': 'Skill-prerequisite graph'},
    {'id': 34, 'category': 'B', 'name': 'Education-transfer graph'},
    {'id': 35, 'category': 'B', 'name': 'Scientific citation graph'},
    {'id': 36, 'category': 'B', 'name': 'Cross-domain analogy graph'},
    {'id': 37, 'category': 'B', 'name': 'Research dependency graph'},
    {'id': 38, 'category': 'B', 'name': 'Resource dependency graph'},
    {'id': 39, 'category': 'B', 'name': 'Theory-to-invention graph'},
    {'id': 40, 'category': 'B', 'name': 'Idea mutation graph'},
    {'id': 41, 'category': 'C', 'name': 'Observation-to-belief pipeline'},
    {'id': 42, 'category': 'C', 'name': 'Hypothesis generation engine'},
    {'id': 43, 'category': 'C', 'name': 'Hypothesis rejection engine'},
    {'id': 44, 'category': 'C', 'name': 'Replication threshold system'},
    {'id': 45, 'category': 'C', 'name': 'Conflicting evidence resolver'},
    {'id': 46, 'category': 'C', 'name': 'Discovery confidence scoring'},
    {'id': 47, 'category': 'C', 'name': 'Discovery maturity levels'},
    {'id': 48, 'category': 'C', 'name': 'Discovery peer-review stages'},
    {'id': 49, 'category': 'C', 'name': 'Discovery fraud risk score'},
    {'id': 50, 'category': 'C', 'name': 'Discovery teaching requirement'},
    {'id': 51, 'category': 'C', 'name': 'Discovery publication requirement'},
    {'id': 52, 'category': 'C', 'name': 'Discovery instrumentation requirement'},
    {'id': 53, 'category': 'C', 'name': 'Discovery safety requirement'},
    {'id': 54, 'category': 'C', 'name': 'Discovery manufacturing requirement'},
    {'id': 55, 'category': 'C', 'name': 'Discovery cultural acceptance'},
    {'id': 56, 'category': 'C', 'name': 'Discovery institutional acceptance'},
    {'id': 57, 'category': 'C', 'name': 'Discovery decay risk'},
    {'id': 58, 'category': 'C', 'name': 'Discovery suppression risk'},
    {'id': 59, 'category': 'C', 'name': 'Discovery rediscovery bonus'},
    {'id': 60, 'category': 'C', 'name': 'Discovery prestige scoring'},
    {'id': 61, 'category': 'D', 'name': 'Reality-depth index'},
    {'id': 62, 'category': 'D', 'name': 'Measurement-resolution ladder'},
    {'id': 63, 'category': 'D', 'name': 'Multi-fidelity solver router'},
    {'id': 64, 'category': 'D', 'name': 'Hidden truth layer'},
    {'id': 65, 'category': 'D', 'name': 'Observed belief layer'},
    {'id': 66, 'category': 'D', 'name': 'Local high-fidelity zones'},
    {'id': 67, 'category': 'D', 'name': 'Global low-fidelity approximation'},
    {'id': 68, 'category': 'D', 'name': 'Surrogate simulation models'},
    {'id': 69, 'category': 'D', 'name': 'Simulation domain validity'},
    {'id': 70, 'category': 'D', 'name': 'Solver credibility score'},
    {'id': 71, 'category': 'D', 'name': 'Simulation cost estimator'},
    {'id': 72, 'category': 'D', 'name': 'Simulation uncertainty score'},
    {'id': 73, 'category': 'D', 'name': 'Simulation convergence tracker'},
    {'id': 74, 'category': 'D', 'name': 'Simulation replay engine'},
    {'id': 75, 'category': 'D', 'name': 'Simulation fork comparison'},
    {'id': 76, 'category': 'D', 'name': 'Simulation snapshot compression'},
    {'id': 77, 'category': 'D', 'name': 'Simulation anomaly detector'},
    {'id': 78, 'category': 'D', 'name': 'Simulation artifact detector'},
    {'id': 79, 'category': 'D', 'name': 'Simulation calibration loop'},
    {'id': 80, 'category': 'D', 'name': 'Simulation provenance ledger'},
    {'id': 81, 'category': 'E', 'name': 'Instrument dependency graph'},
    {'id': 82, 'category': 'E', 'name': 'Instrument calibration drift'},
    {'id': 83, 'category': 'E', 'name': 'Instrument resolution limits'},
    {'id': 84, 'category': 'E', 'name': 'Instrument operator skill effect'},
    {'id': 85, 'category': 'E', 'name': 'Instrument maintenance decay'},
    {'id': 86, 'category': 'E', 'name': 'Instrument contamination risk'},
    {'id': 87, 'category': 'E', 'name': 'Instrument chain-of-custody'},
    {'id': 88, 'category': 'E', 'name': 'Instrument upgrade paths'},
    {'id': 89, 'category': 'E', 'name': 'Instrument reproducibility score'},
    {'id': 90, 'category': 'E', 'name': 'Instrument sensitivity curves'},
    {'id': 91, 'category': 'E', 'name': 'Instrument noise profiles'},
    {'id': 92, 'category': 'E', 'name': 'Instrument environmental limits'},
    {'id': 93, 'category': 'E', 'name': 'Instrument failure signatures'},
    {'id': 94, 'category': 'E', 'name': 'Instrument standardisation system'},
    {'id': 95, 'category': 'E', 'name': 'Instrument invention pathway'},
    {'id': 96, 'category': 'E', 'name': 'Instrument teaching pathway'},
    {'id': 97, 'category': 'E', 'name': 'Instrument misuse risk'},
    {'id': 98, 'category': 'E', 'name': 'Instrument automation layer'},
    {'id': 99, 'category': 'E', 'name': 'Instrument simulation twin'},
    {'id': 100, 'category': 'E', 'name': 'Instrument comparison tests'},
    {'id': 101, 'category': 'F', 'name': 'Design-of-experiments engine'},
    {'id': 102, 'category': 'F', 'name': 'Bayesian optimisation planner'},
    {'id': 103, 'category': 'F', 'name': 'Active learning planner'},
    {'id': 104, 'category': 'F', 'name': 'Gaussian-process optimiser'},
    {'id': 105, 'category': 'F', 'name': 'Multi-armed bandit optimiser'},
    {'id': 106, 'category': 'F', 'name': 'Latin hypercube sampler'},
    {'id': 107, 'category': 'F', 'name': 'Factorial experiment planner'},
    {'id': 108, 'category': 'F', 'name': 'Response surface model'},
    {'id': 109, 'category': 'F', 'name': 'Experiment queue scheduler'},
    {'id': 110, 'category': 'F', 'name': 'Experiment cost estimator'},
    {'id': 111, 'category': 'F', 'name': 'Experiment safety gate'},
    {'id': 112, 'category': 'F', 'name': 'Experiment contamination tracker'},
    {'id': 113, 'category': 'F', 'name': 'Experiment replication manager'},
    {'id': 114, 'category': 'F', 'name': 'Experiment control checker'},
    {'id': 115, 'category': 'F', 'name': 'Experiment deviation logger'},
    {'id': 116, 'category': 'F', 'name': 'Experiment failure analysis'},
    {'id': 117, 'category': 'F', 'name': 'Experiment result parser'},
    {'id': 118, 'category': 'F', 'name': 'Experiment anomaly escalation'},
    {'id': 119, 'category': 'F', 'name': 'Experiment publication package'},
    {'id': 120, 'category': 'F', 'name': 'Experiment confidence ledger'},
    {'id': 121, 'category': 'G', 'name': 'Autonomous lab planner'},
    {'id': 122, 'category': 'G', 'name': 'Virtual lab robot controller'},
    {'id': 123, 'category': 'G', 'name': 'Robotic protocol compiler'},
    {'id': 124, 'category': 'G', 'name': 'Lab task scheduler'},
    {'id': 125, 'category': 'G', 'name': 'Lab sample tracker'},
    {'id': 126, 'category': 'G', 'name': 'LIMS system'},
    {'id': 127, 'category': 'G', 'name': 'Electronic lab notebook'},
    {'id': 128, 'category': 'G', 'name': 'Assay registry'},
    {'id': 129, 'category': 'G', 'name': 'Reagent inventory engine'},
    {'id': 130, 'category': 'G', 'name': 'Sample chain-of-custody'},
    {'id': 131, 'category': 'G', 'name': 'Robotic pipetting module'},
    {'id': 132, 'category': 'G', 'name': 'Robotic heating module'},
    {'id': 133, 'category': 'G', 'name': 'Robotic cooling module'},
    {'id': 134, 'category': 'G', 'name': 'Robotic imaging module'},
    {'id': 135, 'category': 'G', 'name': 'Robotic synthesis module'},
    {'id': 136, 'category': 'G', 'name': 'Robotic sequencing module'},
    {'id': 137, 'category': 'G', 'name': 'Robotic cleaning module'},
    {'id': 138, 'category': 'G', 'name': 'Robotic error detection'},
    {'id': 139, 'category': 'G', 'name': 'Lab contamination model'},
    {'id': 140, 'category': 'G', 'name': 'Lab throughput optimiser'},
    {'id': 141, 'category': 'H', 'name': 'Patent ingestion engine'},
    {'id': 142, 'category': 'H', 'name': 'CPC/IPC classifier'},
    {'id': 143, 'category': 'H', 'name': 'Claim chunker'},
    {'id': 144, 'category': 'H', 'name': 'Independent claim detector'},
    {'id': 145, 'category': 'H', 'name': 'Dependent claim linker'},
    {'id': 146, 'category': 'H', 'name': 'Patent drawing parser'},
    {'id': 147, 'category': 'H', 'name': 'Patent mechanism extractor'},
    {'id': 148, 'category': 'H', 'name': 'Patent material extractor'},
    {'id': 149, 'category': 'H', 'name': 'Patent geometry extractor'},
    {'id': 150, 'category': 'H', 'name': 'Patent process extractor'},
    {'id': 151, 'category': 'H', 'name': 'Patent failure-mode extractor'},
    {'id': 152, 'category': 'H', 'name': 'Patent function mapper'},
    {'id': 153, 'category': 'H', 'name': 'Patent citation graph'},
    {'id': 154, 'category': 'H', 'name': 'Expired patent detector'},
    {'id': 155, 'category': 'H', 'name': 'Active patent conflict detector'},
    {'id': 156, 'category': 'H', 'name': 'Prior-art search engine'},
    {'id': 157, 'category': 'H', 'name': 'Obviousness risk scorer'},
    {'id': 158, 'category': 'H', 'name': 'Patent cluster heatmap'},
    {'id': 159, 'category': 'H', 'name': 'Patent whitespace detector'},
    {'id': 160, 'category': 'H', 'name': 'Patent-to-blueprint compiler'},
    {'id': 161, 'category': 'I', 'name': 'Invention disclosure generator'},
    {'id': 162, 'category': 'I', 'name': 'Claim skeleton generator'},
    {'id': 163, 'category': 'I', 'name': 'Prototype BOM generator'},
    {'id': 164, 'category': 'I', 'name': 'Validation plan generator'},
    {'id': 165, 'category': 'I', 'name': 'Prior-art map generator'},
    {'id': 166, 'category': 'I', 'name': 'Novelty hypothesis scorer'},
    {'id': 167, 'category': 'I', 'name': 'Freedom-to-operate risk score'},
    {'id': 168, 'category': 'I', 'name': 'Technology readiness graph'},
    {'id': 169, 'category': 'I', 'name': 'TRL progression tracker'},
    {'id': 170, 'category': 'I', 'name': 'Prototype test planner'},
    {'id': 171, 'category': 'I', 'name': 'Manufacturing feasibility gate'},
    {'id': 172, 'category': 'I', 'name': 'Commercial use-case mapper'},
    {'id': 173, 'category': 'I', 'name': 'Licensing scenario engine'},
    {'id': 174, 'category': 'I', 'name': 'Spinout simulation layer'},
    {'id': 175, 'category': 'I', 'name': 'Patent portfolio simulator'},
    {'id': 176, 'category': 'I', 'name': 'Invention lineage tracker'},
    {'id': 177, 'category': 'I', 'name': 'Invention recombination engine'},
    {'id': 178, 'category': 'I', 'name': 'Cross-patent mechanism merger'},
    {'id': 179, 'category': 'I', 'name': 'Invention abandonment tracker'},
    {'id': 180, 'category': 'I', 'name': 'Public-domain mechanism miner'},
    {'id': 181, 'category': 'J', 'name': 'Material truth database'},
    {'id': 182, 'category': 'J', 'name': 'Material processing history'},
    {'id': 183, 'category': 'J', 'name': 'Crystal structure registry'},
    {'id': 184, 'category': 'J', 'name': 'Defect density model'},
    {'id': 185, 'category': 'J', 'name': 'Impurity profile system'},
    {'id': 186, 'category': 'J', 'name': 'Phase diagram engine'},
    {'id': 187, 'category': 'J', 'name': 'Alloy discovery engine'},
    {'id': 188, 'category': 'J', 'name': 'Ceramic discovery engine'},
    {'id': 189, 'category': 'J', 'name': 'Polymer discovery engine'},
    {'id': 190, 'category': 'J', 'name': 'Composite material engine'},
    {'id': 191, 'category': 'J', 'name': 'Superconductor candidate engine'},
    {'id': 192, 'category': 'J', 'name': 'Semiconductor candidate engine'},
    {'id': 193, 'category': 'J', 'name': 'Photonic material scorer'},
    {'id': 194, 'category': 'J', 'name': 'Battery material scorer'},
    {'id': 195, 'category': 'J', 'name': 'Catalyst material scorer'},
    {'id': 196, 'category': 'J', 'name': 'Corrosion model'},
    {'id': 197, 'category': 'J', 'name': 'Fatigue material model'},
    {'id': 198, 'category': 'J', 'name': 'Fracture toughness tracker'},
    {'id': 199, 'category': 'J', 'name': 'Thermal conductivity mapper'},
    {'id': 200, 'category': 'J', 'name': 'Electrical conductivity mapper'},
    {'id': 201, 'category': 'K', 'name': 'Manufacturing capability graph'},
    {'id': 202, 'category': 'K', 'name': 'Tolerance limit system'},
    {'id': 203, 'category': 'K', 'name': 'Cleanroom class gate'},
    {'id': 204, 'category': 'K', 'name': 'Process recipe compiler'},
    {'id': 205, 'category': 'K', 'name': 'Defect-rate model'},
    {'id': 206, 'category': 'K', 'name': 'Yield prediction engine'},
    {'id': 207, 'category': 'K', 'name': 'Tooling requirement graph'},
    {'id': 208, 'category': 'K', 'name': 'Jig/fixture design layer'},
    {'id': 209, 'category': 'K', 'name': 'Casting capability model'},
    {'id': 210, 'category': 'K', 'name': 'Forging capability model'},
    {'id': 211, 'category': 'K', 'name': 'Machining capability model'},
    {'id': 212, 'category': 'K', 'name': 'Lithography capability model'},
    {'id': 213, 'category': 'K', 'name': 'Deposition capability model'},
    {'id': 214, 'category': 'K', 'name': 'Etching capability model'},
    {'id': 215, 'category': 'K', 'name': 'Wafer yield simulator'},
    {'id': 216, 'category': 'K', 'name': 'Quality control layer'},
    {'id': 217, 'category': 'K', 'name': 'Statistical process control'},
    {'id': 218, 'category': 'K', 'name': 'Supply substitution engine'},
    {'id': 219, 'category': 'K', 'name': 'Manufacturing bottleneck detector'},
    {'id': 220, 'category': 'K', 'name': 'Scale-up risk model'},
    {'id': 221, 'category': 'L', 'name': 'Resource dependency graph'},
    {'id': 222, 'category': 'L', 'name': 'Supply chain nodes'},
    {'id': 223, 'category': 'L', 'name': 'Bottleneck risk scoring'},
    {'id': 224, 'category': 'L', 'name': 'Substitute material finder'},
    {'id': 225, 'category': 'L', 'name': 'Trade route dependency'},
    {'id': 226, 'category': 'L', 'name': 'Rare earth dependency tracker'},
    {'id': 227, 'category': 'L', 'name': 'Energy dependency tracker'},
    {'id': 228, 'category': 'L', 'name': 'Labour dependency tracker'},
    {'id': 229, 'category': 'L', 'name': 'Tool dependency tracker'},
    {'id': 230, 'category': 'L', 'name': 'Import/export simulation'},
    {'id': 231, 'category': 'L', 'name': 'Supply disruption events'},
    {'id': 232, 'category': 'L', 'name': 'Inventory forecasting'},
    {'id': 233, 'category': 'L', 'name': 'Strategic reserve system'},
    {'id': 234, 'category': 'L', 'name': 'Procurement optimisation'},
    {'id': 235, 'category': 'L', 'name': 'Supplier reliability model'},
    {'id': 236, 'category': 'L', 'name': 'Resource depletion model'},
    {'id': 237, 'category': 'L', 'name': 'Recycling loop engine'},
    {'id': 238, 'category': 'L', 'name': 'Circular economy tracker'},
    {'id': 239, 'category': 'L', 'name': 'Waste stream analyser'},
    {'id': 240, 'category': 'L', 'name': 'Resource conflict predictor'},
    {'id': 241, 'category': 'M', 'name': 'Rigid body solver'},
    {'id': 242, 'category': 'M', 'name': 'Thermodynamic solver'},
    {'id': 243, 'category': 'M', 'name': 'Heat diffusion solver'},
    {'id': 244, 'category': 'M', 'name': 'Combustion model'},
    {'id': 245, 'category': 'M', 'name': 'Phase-change model'},
    {'id': 246, 'category': 'M', 'name': 'Fluid network solver'},
    {'id': 247, 'category': 'M', 'name': 'Shallow-water solver'},
    {'id': 248, 'category': 'M', 'name': 'CFD job connector'},
    {'id': 249, 'category': 'M', 'name': 'Structural beam solver'},
    {'id': 250, 'category': 'M', 'name': 'Finite element connector'},
    {'id': 251, 'category': 'M', 'name': 'Acoustic propagation model'},
    {'id': 252, 'category': 'M', 'name': 'Electromagnetic field model'},
    {'id': 253, 'category': 'M', 'name': 'SPICE circuit connector'},
    {'id': 254, 'category': 'M', 'name': 'RF propagation model'},
    {'id': 255, 'category': 'M', 'name': 'Optical ray tracer'},
    {'id': 256, 'category': 'M', 'name': 'Wave optics module'},
    {'id': 257, 'category': 'M', 'name': 'Plasma physics module'},
    {'id': 258, 'category': 'M', 'name': 'Radiation transport module'},
    {'id': 259, 'category': 'M', 'name': 'Relativity approximation module'},
    {'id': 260, 'category': 'M', 'name': 'Multiphysics coupling manager'},
    {'id': 261, 'category': 'N', 'name': 'DC circuit solver'},
    {'id': 262, 'category': 'N', 'name': 'AC circuit solver'},
    {'id': 263, 'category': 'N', 'name': 'Kirchhoff law discovery'},
    {'id': 264, 'category': 'N', 'name': 'Ohm law discovery'},
    {'id': 265, 'category': 'N', 'name': 'Battery electrochemistry model'},
    {'id': 266, 'category': 'N', 'name': 'Generator model'},
    {'id': 267, 'category': 'N', 'name': 'Motor model'},
    {'id': 268, 'category': 'N', 'name': 'Transformer model'},
    {'id': 269, 'category': 'N', 'name': 'Protection coordination engine'},
    {'id': 270, 'category': 'N', 'name': 'Fuse behaviour model'},
    {'id': 271, 'category': 'N', 'name': 'Circuit breaker model'},
    {'id': 272, 'category': 'N', 'name': 'Arc fault model'},
    {'id': 273, 'category': 'N', 'name': 'Semiconductor band model'},
    {'id': 274, 'category': 'N', 'name': 'Diode discovery path'},
    {'id': 275, 'category': 'N', 'name': 'Transistor discovery path'},
    {'id': 276, 'category': 'N', 'name': 'Integrated circuit path'},
    {'id': 277, 'category': 'N', 'name': 'Microprocessor architecture path'},
    {'id': 278, 'category': 'N', 'name': 'Memory chip path'},
    {'id': 279, 'category': 'N', 'name': 'Sensor electronics path'},
    {'id': 280, 'category': 'N', 'name': 'Power electronics path'},
    {'id': 281, 'category': 'O', 'name': 'Lens discovery path'},
    {'id': 282, 'category': 'O', 'name': 'Refraction model'},
    {'id': 283, 'category': 'O', 'name': 'Reflection model'},
    {'id': 284, 'category': 'O', 'name': 'Prism spectroscopy path'},
    {'id': 285, 'category': 'O', 'name': 'Microscope optics path'},
    {'id': 286, 'category': 'O', 'name': 'Telescope optics path'},
    {'id': 287, 'category': 'O', 'name': 'Laser discovery path'},
    {'id': 288, 'category': 'O', 'name': 'Fibre optics path'},
    {'id': 289, 'category': 'O', 'name': 'Waveguide simulation'},
    {'id': 290, 'category': 'O', 'name': 'Photonic mode graph'},
    {'id': 291, 'category': 'O', 'name': 'Mach-Zehnder mesh model'},
    {'id': 292, 'category': 'O', 'name': 'Microring resonator model'},
    {'id': 293, 'category': 'O', 'name': 'Phase-shifter drift model'},
    {'id': 294, 'category': 'O', 'name': 'Optical loss graph'},
    {'id': 295, 'category': 'O', 'name': 'Photodetector noise model'},
    {'id': 296, 'category': 'O', 'name': 'Optical matrix multiplication'},
    {'id': 297, 'category': 'O', 'name': 'Photonic neural layer'},
    {'id': 298, 'category': 'O', 'name': 'Photonic biosensor module'},
    {'id': 299, 'category': 'O', 'name': 'Quantum photonics interface'},
    {'id': 300, 'category': 'O', 'name': 'Photonic chip calibration'},
    {'id': 301, 'category': 'P', 'name': 'Quantum concept graph'},
    {'id': 302, 'category': 'P', 'name': 'State-vector simulator'},
    {'id': 303, 'category': 'P', 'name': 'Density matrix simulator'},
    {'id': 304, 'category': 'P', 'name': 'Hamiltonian evolution engine'},
    {'id': 305, 'category': 'P', 'name': 'Quantum measurement model'},
    {'id': 306, 'category': 'P', 'name': 'Entanglement detector'},
    {'id': 307, 'category': 'P', 'name': 'Bell test experiment node'},
    {'id': 308, 'category': 'P', 'name': 'Quantum noise model'},
    {'id': 309, 'category': 'P', 'name': 'Decoherence engine'},
    {'id': 310, 'category': 'P', 'name': 'Qubit platform registry'},
    {'id': 311, 'category': 'P', 'name': 'Superconducting qubit model'},
    {'id': 312, 'category': 'P', 'name': 'Trapped ion model'},
    {'id': 313, 'category': 'P', 'name': 'Neutral atom model'},
    {'id': 314, 'category': 'P', 'name': 'Spin qubit model'},
    {'id': 315, 'category': 'P', 'name': 'Photonic qubit model'},
    {'id': 316, 'category': 'P', 'name': 'Quantum error surface map'},
    {'id': 317, 'category': 'P', 'name': 'Error mitigation engine'},
    {'id': 318, 'category': 'P', 'name': 'Quantum error correction graph'},
    {'id': 319, 'category': 'P', 'name': 'Logical qubit tracker'},
    {'id': 320, 'category': 'P', 'name': 'Quantum algorithm registry'},
    {'id': 321, 'category': 'Q', 'name': 'Symmetry graph'},
    {'id': 322, 'category': 'Q', 'name': 'Symmetry-breaking tracker'},
    {'id': 323, 'category': 'Q', 'name': 'Condensed matter phase map'},
    {'id': 324, 'category': 'Q', 'name': 'Floquet system simulator'},
    {'id': 325, 'category': 'Q', 'name': 'Spin chain simulator'},
    {'id': 326, 'category': 'Q', 'name': 'Many-body localisation tracker'},
    {'id': 327, 'category': 'Q', 'name': 'Time-crystal experiment node'},
    {'id': 328, 'category': 'Q', 'name': 'Subharmonic response detector'},
    {'id': 329, 'category': 'Q', 'name': 'Artifact rejection system'},
    {'id': 330, 'category': 'Q', 'name': 'Coherence cycle counter'},
    {'id': 331, 'category': 'Q', 'name': 'Quantum metrology module'},
    {'id': 332, 'category': 'Q', 'name': 'Quantum sensor path'},
    {'id': 333, 'category': 'Q', 'name': 'Quantum memory candidate tracker'},
    {'id': 334, 'category': 'Q', 'name': 'Exotic phase classifier'},
    {'id': 335, 'category': 'Q', 'name': 'Topological matter node'},
    {'id': 336, 'category': 'Q', 'name': 'Anyon candidate simulator'},
    {'id': 337, 'category': 'Q', 'name': 'Superfluid model'},
    {'id': 338, 'category': 'Q', 'name': 'Bose-Einstein condensate path'},
    {'id': 339, 'category': 'Q', 'name': 'Low-temperature lab gate'},
    {'id': 340, 'category': 'Q', 'name': 'Quantum material discovery engine'},
    {'id': 341, 'category': 'R', 'name': 'Genome object system'},
    {'id': 342, 'category': 'R', 'name': 'Chromosome model'},
    {'id': 343, 'category': 'R', 'name': 'Gene object registry'},
    {'id': 344, 'category': 'R', 'name': 'Variant model'},
    {'id': 345, 'category': 'R', 'name': 'Mutation engine'},
    {'id': 346, 'category': 'R', 'name': 'Inheritance engine'},
    {'id': 347, 'category': 'R', 'name': 'Epigenetic state model'},
    {'id': 348, 'category': 'R', 'name': 'Gene regulatory graph'},
    {'id': 349, 'category': 'R', 'name': 'Promoter/enhancer model'},
    {'id': 350, 'category': 'R', 'name': 'Transcription factor graph'},
    {'id': 351, 'category': 'R', 'name': 'Expression state matrix'},
    {'id': 352, 'category': 'R', 'name': 'Cell type registry'},
    {'id': 353, 'category': 'R', 'name': 'Cell-state trajectory graph'},
    {'id': 354, 'category': 'R', 'name': 'Developmental biology timeline'},
    {'id': 355, 'category': 'R', 'name': 'Heritability estimator'},
    {'id': 356, 'category': 'R', 'name': 'Population genetics model'},
    {'id': 357, 'category': 'R', 'name': 'Evolutionary selection model'},
    {'id': 358, 'category': 'R', 'name': 'Speciation tracker'},
    {'id': 359, 'category': 'R', 'name': 'Genetic disease model'},
    {'id': 360, 'category': 'R', 'name': 'Genetic drift model'},
    {'id': 361, 'category': 'S', 'name': 'Protein sequence registry'},
    {'id': 362, 'category': 'S', 'name': 'Protein structure tracker'},
    {'id': 363, 'category': 'S', 'name': 'Protein folding model connector'},
    {'id': 364, 'category': 'S', 'name': 'Protein interaction graph'},
    {'id': 365, 'category': 'S', 'name': 'Protein cluster graph'},
    {'id': 366, 'category': 'S', 'name': 'Binding pocket detector'},
    {'id': 367, 'category': 'S', 'name': 'Ligand docking connector'},
    {'id': 368, 'category': 'S', 'name': 'Binding affinity scorer'},
    {'id': 369, 'category': 'S', 'name': 'Protein stability scorer'},
    {'id': 370, 'category': 'S', 'name': 'Protein misfolding model'},
    {'id': 371, 'category': 'S', 'name': 'Enzyme kinetics model'},
    {'id': 372, 'category': 'S', 'name': 'Antibody candidate engine'},
    {'id': 373, 'category': 'S', 'name': 'Protein design workspace'},
    {'id': 374, 'category': 'S', 'name': 'Protein mutation effect predictor'},
    {'id': 375, 'category': 'S', 'name': 'Protein complex model'},
    {'id': 376, 'category': 'S', 'name': 'Pathway protein map'},
    {'id': 377, 'category': 'S', 'name': 'Molecular dynamics connector'},
    {'id': 378, 'category': 'S', 'name': 'Molecular mechanism graph'},
    {'id': 379, 'category': 'S', 'name': 'Drug-target interaction tracker'},
    {'id': 380, 'category': 'S', 'name': 'Protein patent mapper'},
    {'id': 381, 'category': 'T', 'name': 'Disease ontology graph'},
    {'id': 382, 'category': 'T', 'name': 'Disease progression timeline'},
    {'id': 383, 'category': 'T', 'name': 'Symptom clustering engine'},
    {'id': 384, 'category': 'T', 'name': 'Biomarker discovery engine'},
    {'id': 385, 'category': 'T', 'name': 'Pathway disruption model'},
    {'id': 386, 'category': 'T', 'name': 'Immune response model'},
    {'id': 387, 'category': 'T', 'name': 'Pathogen evolution model'},
    {'id': 388, 'category': 'T', 'name': 'Viral mutation model'},
    {'id': 389, 'category': 'T', 'name': 'Bacterial resistance model'},
    {'id': 390, 'category': 'T', 'name': 'Cancer evolution model'},
    {'id': 391, 'category': 'T', 'name': 'Autoimmune dynamics model'},
    {'id': 392, 'category': 'T', 'name': 'Metabolic disease model'},
    {'id': 393, 'category': 'T', 'name': 'Neurodegeneration model'},
    {'id': 394, 'category': 'T', 'name': 'Perturbation graph'},
    {'id': 395, 'category': 'T', 'name': 'Drug perturbation engine'},
    {'id': 396, 'category': 'T', 'name': 'Gene knockout simulator'},
    {'id': 397, 'category': 'T', 'name': 'Gene knockdown simulator'},
    {'id': 398, 'category': 'T', 'name': 'Overexpression simulator'},
    {'id': 399, 'category': 'T', 'name': 'Therapy candidate scorer'},
    {'id': 400, 'category': 'T', 'name': 'Wet-lab validation planner'},
    {'id': 401, 'category': 'U', 'name': 'Genetic circuit designer'},
    {'id': 402, 'category': 'U', 'name': 'Synthetic promoter library'},
    {'id': 403, 'category': 'U', 'name': 'CRISPR design module'},
    {'id': 404, 'category': 'U', 'name': 'Guide RNA scorer'},
    {'id': 405, 'category': 'U', 'name': 'Off-target risk predictor'},
    {'id': 406, 'category': 'U', 'name': 'Engineered microbe designer'},
    {'id': 407, 'category': 'U', 'name': 'Enzyme pathway optimiser'},
    {'id': 408, 'category': 'U', 'name': 'Biosensor organism module'},
    {'id': 409, 'category': 'U', 'name': 'Cell therapy candidate tracker'},
    {'id': 410, 'category': 'U', 'name': 'Gene therapy vector selector'},
    {'id': 411, 'category': 'U', 'name': 'Delivery vehicle scorer'},
    {'id': 412, 'category': 'U', 'name': 'Biomanufacturing process model'},
    {'id': 413, 'category': 'U', 'name': 'Fermentation optimisation engine'},
    {'id': 414, 'category': 'U', 'name': 'Bioreactor simulation'},
    {'id': 415, 'category': 'U', 'name': 'Containment safety layer'},
    {'id': 416, 'category': 'U', 'name': 'Biosecurity risk layer'},
    {'id': 417, 'category': 'U', 'name': 'Synthetic pathway patent mapper'},
    {'id': 418, 'category': 'U', 'name': 'Living material engine'},
    {'id': 419, 'category': 'U', 'name': 'Tissue engineering module'},
    {'id': 420, 'category': 'U', 'name': 'Organoid simulation layer'},
    {'id': 421, 'category': 'V', 'name': 'Foundation model registry'},
    {'id': 422, 'category': 'V', 'name': 'Language model tracker'},
    {'id': 423, 'category': 'V', 'name': 'Vision model tracker'},
    {'id': 424, 'category': 'V', 'name': 'Protein model tracker'},
    {'id': 425, 'category': 'V', 'name': 'Cell model tracker'},
    {'id': 426, 'category': 'V', 'name': 'Materials model tracker'},
    {'id': 427, 'category': 'V', 'name': 'Chemistry model tracker'},
    {'id': 428, 'category': 'V', 'name': 'Patent model tracker'},
    {'id': 429, 'category': 'V', 'name': 'Robotics model tracker'},
    {'id': 430, 'category': 'V', 'name': 'Quantum circuit model tracker'},
    {'id': 431, 'category': 'V', 'name': 'Dataset lineage system'},
    {'id': 432, 'category': 'V', 'name': 'Data nutrition score'},
    {'id': 433, 'category': 'V', 'name': 'Bias profile tracker'},
    {'id': 434, 'category': 'V', 'name': 'Missingness tracker'},
    {'id': 435, 'category': 'V', 'name': 'Model evaluation arena'},
    {'id': 436, 'category': 'V', 'name': 'Model drift detector'},
    {'id': 437, 'category': 'V', 'name': 'Model hallucination detector'},
    {'id': 438, 'category': 'V', 'name': 'Model uncertainty estimator'},
    {'id': 439, 'category': 'V', 'name': 'Model distillation system'},
    {'id': 440, 'category': 'V', 'name': 'Model capability graph'},
    {'id': 441, 'category': 'W', 'name': 'Research swarm system'},
    {'id': 442, 'category': 'W', 'name': 'Literature miner agent'},
    {'id': 443, 'category': 'W', 'name': 'Patent miner agent'},
    {'id': 444, 'category': 'W', 'name': 'Mechanism extractor agent'},
    {'id': 445, 'category': 'W', 'name': 'Experimentalist agent'},
    {'id': 446, 'category': 'W', 'name': 'Simulation engineer agent'},
    {'id': 447, 'category': 'W', 'name': 'Instrument specialist agent'},
    {'id': 448, 'category': 'W', 'name': 'Statistician agent'},
    {'id': 449, 'category': 'W', 'name': 'Skeptic agent'},
    {'id': 450, 'category': 'W', 'name': 'Safety officer agent'},
    {'id': 451, 'category': 'W', 'name': 'Standards officer agent'},
    {'id': 452, 'category': 'W', 'name': 'Claims drafter agent'},
    {'id': 453, 'category': 'W', 'name': 'Principal investigator agent'},
    {'id': 454, 'category': 'W', 'name': 'Lab technician agent'},
    {'id': 455, 'category': 'W', 'name': 'Data curator agent'},
    {'id': 456, 'category': 'W', 'name': 'Peer reviewer agent'},
    {'id': 457, 'category': 'W', 'name': 'Replication agent'},
    {'id': 458, 'category': 'W', 'name': 'Commercialisation agent'},
    {'id': 459, 'category': 'W', 'name': 'Ethics gate agent'},
    {'id': 460, 'category': 'W', 'name': 'Red-team science agent'},
    {'id': 461, 'category': 'X', 'name': 'School system graph'},
    {'id': 462, 'category': 'X', 'name': 'Apprenticeship engine'},
    {'id': 463, 'category': 'X', 'name': 'University formation system'},
    {'id': 464, 'category': 'X', 'name': 'Laboratory institution system'},
    {'id': 465, 'category': 'X', 'name': 'Journal publication system'},
    {'id': 466, 'category': 'X', 'name': 'Peer review network'},
    {'id': 467, 'category': 'X', 'name': 'Standards body engine'},
    {'id': 468, 'category': 'X', 'name': 'Patent office engine'},
    {'id': 469, 'category': 'X', 'name': 'Technology transfer office'},
    {'id': 470, 'category': 'X', 'name': 'Guild specialisation system'},
    {'id': 471, 'category': 'X', 'name': 'Scientific labour market'},
    {'id': 472, 'category': 'X', 'name': 'Expert scarcity model'},
    {'id': 473, 'category': 'X', 'name': 'Knowledge preservation system'},
    {'id': 474, 'category': 'X', 'name': 'Library redundancy model'},
    {'id': 475, 'category': 'X', 'name': 'Language translation engine'},
    {'id': 476, 'category': 'X', 'name': 'Curriculum evolution engine'},
    {'id': 477, 'category': 'X', 'name': 'Credentialing system'},
    {'id': 478, 'category': 'X', 'name': 'Academic politics simulator'},
    {'id': 479, 'category': 'X', 'name': 'Funding allocation engine'},
    {'id': 480, 'category': 'X', 'name': 'Institutional credibility tracker'},
    {'id': 481, 'category': 'Y', 'name': 'Knowledge graph visualiser'},
    {'id': 482, 'category': 'Y', 'name': 'Temporal graph visualiser'},
    {'id': 483, 'category': 'Y', 'name': 'Patent cluster map'},
    {'id': 484, 'category': 'Y', 'name': 'Research frontier dashboard'},
    {'id': 485, 'category': 'Y', 'name': 'Experiment queue dashboard'},
    {'id': 486, 'category': 'Y', 'name': 'Civilisation reality index UI'},
    {'id': 487, 'category': 'Y', 'name': 'Institution health UI'},
    {'id': 488, 'category': 'Y', 'name': 'Discovery evidence viewer'},
    {'id': 489, 'category': 'Y', 'name': 'Timeline fork viewer'},
    {'id': 490, 'category': 'Y', 'name': 'Simulation replay viewer'},
    {'id': 491, 'category': 'Y', 'name': 'Patent scanner interface'},
    {'id': 492, 'category': 'Y', 'name': 'Gateway challenge system'},
    {'id': 493, 'category': 'Y', 'name': 'Minion thought inspector'},
    {'id': 494, 'category': 'Y', 'name': 'Scientific dispute viewer'},
    {'id': 495, 'category': 'Y', 'name': 'Anomaly alert console'},
    {'id': 496, 'category': 'Y', 'name': 'Failure-mode dashboard'},
    {'id': 497, 'category': 'Y', 'name': 'Invention disclosure workspace'},
    {'id': 498, 'category': 'Y', 'name': 'Research swarm command centre'},
    {'id': 499, 'category': 'Y', 'name': 'Digital twin inspection mode'},
    {'id': 500, 'category': 'Y', 'name': 'Grand civilisation map'},
]
