"""Real computational-linguistics methods (in-world simulations).

Eight genuine, named algorithms from NLP / information theory — not stubs or
external connectors. Each is implemented with numpy / collections and is
verified against a KNOWN ground-truth value in the test suite:

  1. Zipf's law rank-frequency fit   -> log-log slope ~= -1 on Zipfian data
  2. n-gram language-model perplexity -> lower perplexity for in-distribution text
  3. TF-IDF term weighting            -> rare term weighted higher than common
  4. Levenshtein edit distance        -> "kitten"->"sitting" = 3
  5. Cosine similarity (bag-of-words) -> identical documents = 1.0
  6. Shannon entropy / bits-per-char  -> English raw ~= 4 bits/char
  7. Heaps' law vocabulary growth     -> V = K * N**beta, beta in 0.4-0.6
  8. BLEU score n-gram overlap        -> perfect match = 1.0

All functions return plain dicts of JSON-serialisable values.
"""
from __future__ import annotations

import math
import re
from collections import Counter

import numpy as np

SIMULATION = {"simulation": True, "physical_hardware": False}


def _tokenize(text: str) -> list[str]:
    """Lowercase word tokenizer (alphanumeric runs)."""
    return re.findall(r"[a-z0-9]+", text.lower())


# ---------------------------------------------------------------------------
# 1. Zipf's law rank-frequency fit
# ---------------------------------------------------------------------------
def zipf_law_fit(frequencies: list[int] | None = None) -> dict:
    """Fit Zipf's law: frequency ~ rank ** (-s) by least squares in log-log.

    On data generated by f(r) = C / r (an ideal Zipfian distribution) the
    log-log slope equals -s = -1 (KNOWN). We synthesise such data when no
    frequencies are supplied so the verification is exact.

    Returns the fitted slope (which should be ~ -1) and exponent s.
    """
    if frequencies is None:
        # Ideal Zipfian: f(r) = N / r  with N = 100000, ranks 1..1000.
        ranks = np.arange(1, 1001)
        frequencies = (100000.0 / ranks).tolist()

    freqs = np.asarray(sorted((float(f) for f in frequencies), reverse=True))
    ranks = np.arange(1, len(freqs) + 1, dtype=float)

    log_r = np.log(ranks)
    log_f = np.log(freqs)
    # Linear fit log_f = slope * log_r + intercept.
    slope, intercept = np.polyfit(log_r, log_f, 1)

    # Coefficient of determination.
    pred = slope * log_r + intercept
    ss_res = float(np.sum((log_f - pred) ** 2))
    ss_tot = float(np.sum((log_f - log_f.mean()) ** 2))
    r_squared = 1.0 - ss_res / ss_tot if ss_tot > 0 else 1.0

    return {
        "method": "zipf_law_fit",
        "slope": float(slope),
        "exponent_s": float(-slope),
        "intercept": float(intercept),
        "r_squared": float(r_squared),
        "n_ranks": int(len(freqs)),
        **SIMULATION,
    }


# ---------------------------------------------------------------------------
# 2. n-gram language-model perplexity
# ---------------------------------------------------------------------------
def ngram_perplexity(train_text: str | None = None,
                     test_text: str | None = None,
                     n: int = 2,
                     vocab_smoothing: float = 1.0) -> dict:
    """Train an n-gram (default bigram) model with add-k (Laplace) smoothing
    and compute perplexity of test text.

    Perplexity = exp(-(1/M) * sum log P(w_i | context)).
    KNOWN behaviour: text drawn from the training distribution yields a lower
    perplexity than out-of-distribution text. We return perplexity for an
    in-distribution probe and an out-of-distribution probe for comparison.
    """
    if train_text is None:
        train_text = ("the cat sat on the mat the cat ate the fish "
                      "the dog sat on the log the dog ate the bone ") * 5
    train = _tokenize(train_text)

    # Build (n-1)-gram context counts and n-gram counts.
    context_counts: Counter = Counter()
    ngram_counts: Counter = Counter()
    for i in range(len(train) - n + 1):
        gram = tuple(train[i:i + n])
        ngram_counts[gram] += 1
        context_counts[gram[:-1]] += 1
    vocab = set(train)
    V = len(vocab)

    def _perplexity(tokens: list[str]) -> float:
        if len(tokens) < n:
            return float("inf")
        log_prob = 0.0
        count = 0
        for i in range(len(tokens) - n + 1):
            gram = tuple(tokens[i:i + n])
            ctx = gram[:-1]
            num = ngram_counts.get(gram, 0) + vocab_smoothing
            den = context_counts.get(ctx, 0) + vocab_smoothing * V
            prob = num / den
            log_prob += math.log(prob)
            count += 1
        return math.exp(-log_prob / count)

    in_dist = test_text if test_text is not None else "the cat sat on the mat"
    out_dist = "quantum helicopter avalanche purple xylophone glitch"

    ppl_in = _perplexity(_tokenize(in_dist))
    ppl_out = _perplexity(_tokenize(out_dist))

    return {
        "method": "ngram_perplexity",
        "n": int(n),
        "vocab_size": int(V),
        "perplexity_in_distribution": float(ppl_in),
        "perplexity_out_of_distribution": float(ppl_out),
        "in_lower_than_out": bool(ppl_in < ppl_out),
        **SIMULATION,
    }


# ---------------------------------------------------------------------------
# 3. TF-IDF term weighting
# ---------------------------------------------------------------------------
def tfidf_weights(documents: list[str] | None = None) -> dict:
    """Compute TF-IDF weights over a small corpus.

    tf(t,d) = count(t,d) / len(d)
    idf(t)  = ln(N / df(t))   (df = number of docs containing t)
    KNOWN behaviour: a term appearing in only one document (rare) receives a
    higher IDF -> higher TF-IDF weight than a term appearing in every document
    (which gets idf = ln(N/N) = 0).
    """
    if documents is None:
        documents = [
            "the cat sat",
            "the dog ran",
            "the bird flew unique",
        ]
    N = len(documents)
    tokenized = [_tokenize(d) for d in documents]

    df: Counter = Counter()
    for toks in tokenized:
        for t in set(toks):
            df[t] += 1

    tfidf: list[dict[str, float]] = []
    for toks in tokenized:
        counts = Counter(toks)
        total = len(toks) or 1
        weights = {}
        for t, c in counts.items():
            tf = c / total
            idf = math.log(N / df[t])
            weights[t] = tf * idf
        tfidf.append(weights)

    # "the" appears in every doc -> idf 0; "unique" appears in 1 doc -> high idf.
    common_term = "the"
    rare_term = "unique"
    common_weight = max(d.get(common_term, 0.0) for d in tfidf)
    rare_weight = max(d.get(rare_term, 0.0) for d in tfidf)

    return {
        "method": "tfidf_weights",
        "n_docs": int(N),
        "idf": {t: float(math.log(N / c)) for t, c in df.items()},
        "tfidf": [{k: float(v) for k, v in d.items()} for d in tfidf],
        "common_term": common_term,
        "common_weight": float(common_weight),
        "rare_term": rare_term,
        "rare_weight": float(rare_weight),
        "rare_weighted_higher": bool(rare_weight > common_weight),
        **SIMULATION,
    }


# ---------------------------------------------------------------------------
# 4. Levenshtein edit distance
# ---------------------------------------------------------------------------
def levenshtein_distance(a: str = "kitten", b: str = "sitting") -> dict:
    """Classic dynamic-programming Levenshtein (insert/delete/substitute = 1).

    KNOWN: distance("kitten", "sitting") = 3.
    """
    m, n = len(a), len(b)
    # dp[i][j] = edit distance between a[:i] and b[:j].
    dp = np.zeros((m + 1, n + 1), dtype=int)
    dp[:, 0] = np.arange(m + 1)
    dp[0, :] = np.arange(n + 1)
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            cost = 0 if a[i - 1] == b[j - 1] else 1
            dp[i, j] = min(
                dp[i - 1, j] + 1,        # deletion
                dp[i, j - 1] + 1,        # insertion
                dp[i - 1, j - 1] + cost  # substitution / match
            )
    distance = int(dp[m, n])
    norm = distance / max(m, n) if max(m, n) else 0.0
    return {
        "method": "levenshtein_distance",
        "a": a,
        "b": b,
        "distance": distance,
        "normalized": float(norm),
        **SIMULATION,
    }


# ---------------------------------------------------------------------------
# 5. Cosine similarity of bag-of-words vectors
# ---------------------------------------------------------------------------
def cosine_similarity_bow(text_a: str | None = None,
                          text_b: str | None = None) -> dict:
    """Cosine similarity of bag-of-words count vectors.

    cos = (u . v) / (|u| |v|).
    KNOWN: identical documents -> similarity = 1.0; documents with no shared
    vocabulary -> 0.0.
    """
    if text_a is None:
        text_a = "the quick brown fox jumps"
    if text_b is None:
        text_b = "the quick brown fox jumps"

    ca, cb = Counter(_tokenize(text_a)), Counter(_tokenize(text_b))
    vocab = sorted(set(ca) | set(cb))
    u = np.array([ca.get(w, 0) for w in vocab], dtype=float)
    v = np.array([cb.get(w, 0) for w in vocab], dtype=float)

    denom = float(np.linalg.norm(u) * np.linalg.norm(v))
    sim = float(np.dot(u, v) / denom) if denom > 0 else 0.0

    return {
        "method": "cosine_similarity_bow",
        "vocab_size": int(len(vocab)),
        "similarity": sim,
        **SIMULATION,
    }


# ---------------------------------------------------------------------------
# 6. Shannon entropy / bits-per-character
# ---------------------------------------------------------------------------
def char_entropy(text: str | None = None) -> dict:
    """First-order Shannon entropy of the character distribution.

    H = -sum p(c) * log2 p(c)   bits per character.
    KNOWN: raw English text (no context model) has a per-character entropy of
    roughly 4 bits/char (the empirical first-order figure; the theoretical
    uniform maximum over 26 letters is log2(26) ~= 4.7). We default to a chunk
    of English prose, whose measured entropy lands in the ~4 bit/char band.
    """
    if text is None:
        text = (
            "the quick brown fox jumps over the lazy dog while the "
            "early morning sunlight streams across the quiet meadow and "
            "the gentle breeze carries the scent of fresh rain over the "
            "rolling hills where sheep graze beneath the open sky"
        )
    # Letters only, lowercased -> models the classic 26/27-symbol alphabet.
    chars = [c for c in text.lower() if c.isalpha()]
    total = len(chars)
    counts = Counter(chars)
    probs = np.array([c / total for c in counts.values()], dtype=float)
    entropy_bits = float(-np.sum(probs * np.log2(probs)))
    max_entropy = float(math.log2(len(counts))) if counts else 0.0

    return {
        "method": "char_entropy",
        "n_chars": int(total),
        "n_symbols": int(len(counts)),
        "bits_per_char": entropy_bits,
        "max_bits_per_char": max_entropy,
        "redundancy": float(1.0 - entropy_bits / max_entropy) if max_entropy else 0.0,
        **SIMULATION,
    }


# ---------------------------------------------------------------------------
# 7. Heaps' law vocabulary growth: V = K * N**beta
# ---------------------------------------------------------------------------
def heaps_law_fit(text: str | None = None, n_points: int = 50) -> dict:
    """Fit Heaps' law V = K * N**beta by least squares in log-log space.

    We accumulate vocabulary size V against tokens seen N, then fit
    log V = log K + beta * log N.
    KNOWN: for natural-language text beta falls in 0.4-0.6. We synthesise a
    Zipfian-distributed token stream (which provably produces a sublinear
    Heaps exponent in that band) when no text is supplied.
    """
    if text is None:
        # Generate tokens by sampling word ranks from a Zipf distribution;
        # Zipfian sampling yields Heaps exponent beta ~ 0.5.
        rng = np.random.default_rng(42)
        # 40000 tokens drawn from a Zipf(a=1.9) law over word ids; the steep
        # exponent saturates the vocabulary into the sublinear Heaps regime
        # (beta ~ 0.5, the natural-language band).
        samples = rng.zipf(1.9, size=40000)
        tokens = [str(s) for s in samples]
    else:
        tokens = _tokenize(text)

    n_total = len(tokens)
    if n_total < 10:
        raise ValueError("need at least 10 tokens for a Heaps fit")

    # Sample N values logarithmically from 1 to n_total.
    Ns = np.unique(np.geomspace(2, n_total, n_points).astype(int))
    seen: set[str] = set()
    Vs = []
    last = 0
    for N in Ns:
        for tok in tokens[last:N]:
            seen.add(tok)
        last = N
        Vs.append(len(seen))
    Vs = np.array(Vs, dtype=float)

    log_N = np.log(Ns.astype(float))
    log_V = np.log(Vs)
    beta, log_K = np.polyfit(log_N, log_V, 1)
    K = float(math.exp(log_K))

    return {
        "method": "heaps_law_fit",
        "K": K,
        "beta": float(beta),
        "n_tokens": int(n_total),
        "vocab_size": int(len(seen)),
        "beta_in_natural_band": bool(0.4 <= beta <= 0.6),
        **SIMULATION,
    }


# ---------------------------------------------------------------------------
# 8. BLEU score n-gram overlap
# ---------------------------------------------------------------------------
def bleu_score(candidate: str | None = None,
               reference: str | None = None,
               max_n: int = 4) -> dict:
    """Sentence-level BLEU with modified n-gram precision and brevity penalty.

    BLEU = BP * exp( (1/N) * sum_n log p_n )
      p_n = clipped n-gram precision
      BP  = 1 if c > r else exp(1 - r/c)
    KNOWN: a candidate identical to the reference scores 1.0.
    """
    if candidate is None:
        candidate = "the cat sat on the mat"
    if reference is None:
        reference = "the cat sat on the mat"

    cand = _tokenize(candidate)
    ref = _tokenize(reference)
    c, r = len(cand), len(ref)

    precisions = []
    for k in range(1, max_n + 1):
        cand_grams = Counter(tuple(cand[i:i + k]) for i in range(len(cand) - k + 1))
        ref_grams = Counter(tuple(ref[i:i + k]) for i in range(len(ref) - k + 1))
        if not cand_grams:
            precisions.append(0.0)
            continue
        clipped = sum(min(cnt, ref_grams.get(g, 0)) for g, cnt in cand_grams.items())
        total = sum(cand_grams.values())
        precisions.append(clipped / total)

    if min(precisions) > 0:
        log_mean = sum(math.log(p) for p in precisions) / len(precisions)
        geo_mean = math.exp(log_mean)
    else:
        geo_mean = 0.0

    # Brevity penalty.
    if c == 0:
        bp = 0.0
    elif c > r:
        bp = 1.0
    else:
        bp = math.exp(1.0 - r / c)

    bleu = bp * geo_mean

    return {
        "method": "bleu_score",
        "precisions": [float(p) for p in precisions],
        "brevity_penalty": float(bp),
        "bleu": float(bleu),
        "candidate_len": int(c),
        "reference_len": int(r),
        **SIMULATION,
    }


# ---------------------------------------------------------------------------
# Route table: keyword tuple -> function
# ---------------------------------------------------------------------------
ROUTE_TABLE: dict[tuple[str, ...], object] = {
    ("zipf", "zipfs_law", "rank_frequency", "linguist", "nlp"): zipf_law_fit,
    ("perplexity", "ngram", "language_model", "lm"): ngram_perplexity,
    ("tfidf", "tf_idf", "term_weighting", "idf"): tfidf_weights,
    ("edit_distance", "levenshtein"): levenshtein_distance,
    ("cosine_sim", "cosine_similarity", "bag_of_words", "bow"): cosine_similarity_bow,
    ("char_entropy", "shannon_entropy", "bits_per_char", "entropy"): char_entropy,
    ("heaps", "heaps_law", "vocabulary_growth"): heaps_law_fit,
    ("bleu", "bleu_score", "ngram_overlap"): bleu_score,
}


def route(keyword: str):
    """Resolve a keyword to its method function (None if unknown)."""
    kw = keyword.strip().lower()
    for keys, fn in ROUTE_TABLE.items():
        if kw in keys:
            return fn
    return None
