"""STORY_ENGINE — the soul layer: science advancement trees + millions of LLM-driven
story templates + emotions + inter-minion interactions.

The render bible (design_spec.py) said how things LOOK; this says what they MEAN and
FEEL. Built from the sim's REAL taxonomies — the 58 ``methods_*`` sciences, 11 guilds,
11 saga archetypes, 7 moods — expanded combinatorially so every science × sub-niche ×
archetype × emotion × era × beat is a distinct story scaffold. Each row carries an
**LLM prompt template**: the actual prose/dialogue is generated by Llama at runtime
(the "real LLM between the minions"), so the CSV is the infinite scaffold, not canned
text.

Outputs (CSV, under underworld/data/design/):
  sciences.csv        — every science × sub-niche × advancement STEP × era (tech trees)
  emotions.csv         — moods/feelings × trigger × expression (anim/vfx/dialogue tone)
  interactions.csv     — minion×minion interaction types × emotion × science (LLM dialogue)
  stories.csv          — archetype × science × sub-niche × emotion × era × beat (MILLIONS),
                         each with an LLM prompt, emotional arc, learning benefit

stdlib only; deterministic; streamed so it scales to millions/billions.
"""

from __future__ import annotations

import csv
import hashlib
import os
from typing import Iterable, Optional

# ── REAL taxonomies (mirror the sim's enums/services) ───────────────────────────────
SCIENCES = [
    "acoustics", "aerodynamics", "agronomy", "astronomy", "atmoschem", "biology",
    "biomechanics", "chemistry", "combustion", "control", "crypto", "crystallography",
    "cs_ai", "earth", "ecology", "economics", "electrochem", "electronics",
    "engineering", "epidemiology", "fluids", "foodscience", "forestry", "geodesy",
    "geology", "geotechnical", "heattransfer", "hydrogeology", "hydrology", "immunology",
    "linguistics", "materials", "math", "medicine", "metallurgy", "neuro", "nuclear",
    "ocean", "optics", "pharmacology", "photovoltaics", "physics", "plasma", "polymer",
    "qcomputing", "quantum", "rf", "robotics", "seismology", "semiconductor", "signal",
    "spectroscopy", "statmech", "structural", "tribology", "veterinary",
]

GUILDS = ["maths", "physics", "electrical", "mechanical", "civil", "materials",
          "computing", "energy", "agriculture", "patent", "safety"]

# 7 real moods + the richer feelings that colour stories
MOODS = ["flow", "inspired", "content", "bored", "anxious", "exhausted", "despairing"]
FEELINGS = ["joy", "grief", "pride", "envy", "wonder", "fear", "love", "ambition",
            "curiosity", "despair", "awe", "resolve", "doubt", "triumph", "longing"]

ERAS = ["stone", "bronze", "iron", "classical", "medieval", "industrial", "modern", "future"]

# The universal advancement spine every science climbs (gated by era + skill).
ADVANCE_STEPS = [
    ("observe", "notices a pattern"), ("question", "asks why"),
    ("hypothesise", "forms a hypothesis"), ("instrument", "builds a tool to measure"),
    ("experiment", "runs an experiment"), ("measure", "takes careful measurements"),
    ("anomaly", "hits an anomaly"), ("model", "fits a model"),
    ("predict", "makes a prediction"), ("verify", "verifies against reality"),
    ("discover", "makes a discovery"), ("name", "names the principle"),
    ("refine", "refines the theory"), ("synthesise", "synthesises with other fields"),
    ("apply", "applies it to a problem"), ("invent", "invents a device"),
    ("patent", "files a patent"), ("teach", "teaches an apprentice"),
    ("publish", "publishes for the guild"), ("master", "achieves mastery"),
]

# saga archetypes (from sagas.py) with their 5 narrative beats
ARCHETYPES = {
    "prodigy":        ["a gifted child emerges", "the first triumph", "the hard lesson", "the rivalry", "ascension"],
    "mentorship":     ["the master takes a pupil", "early failures", "the breakthrough", "surpassing the master", "the torch passes"],
    "great_discovery":["the nagging question", "years in the dark", "the spark", "the world changes", "the legacy"],
    "rivalry":        ["two minds clash", "escalation", "the contest", "the reckoning", "respect or ruin"],
    "plague_trial":   ["the sickness spreads", "the search for a cure", "the desperate trial", "the turning point", "the aftermath"],
    "lost_knowledge": ["a fragment is found", "the hunt", "the decipherment", "the restoration", "rebirth of an art"],
    "renaissance":    ["a guild stagnates", "a heretic idea", "the flourishing", "the golden age", "the new canon"],
    "first_of_kind":  ["the impossible dream", "the doubters", "the build", "the first run", "history made"],
    "legacy":         ["a life's work", "the failing years", "the inheritor", "the completion", "remembered"],
    "wanderer":       ["the restless soul", "strange lands", "the gathered wisdom", "the return", "the changed home"],
    "reconciliation": ["an old wound", "the cold distance", "the overture", "the hard truth", "peace"],
}

INTERACTIONS = [
    ("mentor",     "teaches", "knowledge+,bond+"), ("rival",   "competes", "drive+,stress+"),
    ("romance",    "courts",  "love+,morale+"),     ("collab",  "co-researches", "discovery+,bond+"),
    ("debate",     "argues",  "insight+,tension+"), ("betray",  "betrays", "trust--,grief+"),
    ("console",    "comforts","sanity+,bond+"),     ("trade",   "bargains", "wealth+,social+"),
    ("inspire",    "inspires","morale+,drive+"),    ("challenge","challenges","resolve+,stress+"),
    ("gossip",     "gossips", "social+,reputation~"),("forgive", "forgives", "peace+,sanity+"),
    ("recruit",    "recruits","guild+,bond+"),      ("grieve",  "mourns", "grief+,bond+"),
    ("celebrate",  "celebrates","joy+,morale+"),    ("conflict","fights", "health-,morale-"),
    ("apprentice", "studies under","skill+,bond+"), ("eulogise","honours", "legacy+,awe+"),
]


def _h(*p) -> int:
    return int.from_bytes(hashlib.md5("|".join(map(str, p)).encode()).digest()[:5], "big")


def _pick(seed, opts):
    return opts[seed % len(opts)]


# ~90 REAL research facets — the universal sub-subjects every science is studied through
# (approach × scale × phenomenon × method). 56 sciences × ~90 facets ≈ 5,000 real subjects.
FACETS = [
    # approach
    "theory", "applied", "experimental", "computational", "statistical", "analytical",
    "empirical", "phenomenological", "first_principles", "data_driven", "heuristic",
    # regime / scale
    "quantum", "atomic", "molecular", "nano", "micro", "meso", "macro", "continuum",
    "relativistic", "classical", "stochastic", "deterministic", "nonlinear", "chaotic",
    # state / phase
    "solid_state", "fluid", "plasma", "gas", "crystalline", "amorphous", "surface",
    "interface", "thin_film", "bulk", "porous", "granular", "colloidal",
    # phenomena
    "dynamics", "kinetics", "thermodynamics", "transport", "transfer", "diffusion",
    "conduction", "convection", "radiation", "resonance", "instability", "turbulence",
    "phase_transition", "self_assembly", "growth", "decay", "transformation",
    # methods / techniques
    "spectroscopy", "imaging", "microscopy", "diffraction", "scattering", "tomography",
    "synthesis", "catalysis", "separation", "characterisation", "fabrication",
    "simulation", "modelling", "optimisation", "control", "sensing", "metrology",
    "calibration", "inversion", "reconstruction",
    # systems / applications
    "materials", "devices", "systems", "networks", "structures", "processes",
    "energy", "storage", "conversion", "generation", "detection", "automation",
    "robotics", "intelligence", "safety", "reliability", "scaling", "integration",
    # life / earth / space flavours (read as real wherever applied)
    "biological", "ecological", "geological", "atmospheric", "oceanic", "planetary",
    "stellar", "evolutionary", "genetic", "metabolic", "neural", "immune",
]

# a few genuinely science-specific niches prepended for the headline domains
_FLAVOUR = {
    "chemistry": ["organic", "inorganic", "physical_chem", "analytical_chem", "biochem", "photochem"],
    "physics": ["mechanics", "electromagnetism", "particle", "condensed_matter", "astrophysics", "optics_phys"],
    "biology": ["genomics", "cell_biology", "evolution", "microbiology", "neurobiology", "synthetic_bio"],
    "math": ["algebra", "analysis", "geometry", "number_theory", "topology", "logic"],
    "medicine": ["surgery", "pharmacology_med", "diagnostics", "epidemiology_med", "trauma", "genomic_med"],
    "materials": ["metals", "ceramics", "polymers_mat", "composites", "semiconductors_mat", "biomaterials"],
}


def _sub_niches(science: str) -> list[str]:
    """~90 real sub-subjects per science: science-specific flavour + universal facets.
    56 sciences × ~90 ≈ 5,000 distinct research subjects across the world."""
    return _FLAVOUR.get(science, []) + FACETS


# ── generators ──────────────────────────────────────────────────────────────────────
def gen_sciences() -> Iterable[dict]:
    """Every science × sub-niche × advancement step × era — the tech trees the guilds
    climb. ~58×6×20×8 ≈ 55k rows."""
    for sci in SCIENCES:
        for ni, niche in enumerate(_sub_niches(sci)):
            for si, (step, verb) in enumerate(ADVANCE_STEPS):
                for ei, era in enumerate(ERAS):
                    # a step is reachable once the era is advanced enough for it
                    gate = int(si * len(ERAS) / len(ADVANCE_STEPS))
                    yield {
                        "science": sci, "sub_niche": niche, "step": step, "step_index": si,
                        "era": era, "reachable": int(ei >= gate),
                        "skill_req": round(1.0 + si * 0.6, 1),
                        "verb": verb,
                        "unlocks": ADVANCE_STEPS[min(si + 1, len(ADVANCE_STEPS) - 1)][0],
                        "knowledge_yield": si + 1,
                        "discovery_chance": round(min(0.9, 0.05 + si * 0.045), 3),
                        "llm_prompt": (f"A {{guild}} minion working on {sci}/{niche} in the "
                                       f"{era} era {verb}. Describe the moment in one vivid, "
                                       f"technically-grounded sentence."),
                    }


def gen_emotions() -> Iterable[dict]:
    anim = {"flow": "study", "inspired": "celebrate", "content": "idle", "bored": "idle",
            "anxious": "rest", "exhausted": "rest", "despairing": "rest"}
    for mood in MOODS:
        for feel in FEELINGS:
            yield {
                "mood": mood, "feeling": feel,
                "intensity": round(0.4 + (_h(mood, feel) % 60) / 100.0, 2),
                "anim": anim.get(mood, "idle"),
                "vfx": _pick(_h(feel), ["", "vfx_aura", "vfx_tear", "vfx_spark", "vfx_glow"]),
                "dialogue_tone": _pick(_h(mood, feel), ["measured", "fervent", "weary",
                                       "bitter", "tender", "exultant", "hollow", "wry"]),
                "face": _pick(_h(feel, mood), ["neutral", "smile", "frown", "wide_eyed",
                              "downcast", "clenched", "serene"]),
                "llm_prompt": (f"Write a line of inner monologue for a minion who is "
                               f"{mood} and feels {feel}. One sentence, in character."),
            }


def gen_interactions() -> Iterable[dict]:
    for kind, verb, eff in INTERACTIONS:
        for mood in MOODS:
            for sci in SCIENCES:
                yield {
                    "interaction": kind, "verb": verb, "mood": mood, "science": sci,
                    "effects": eff,
                    "anim_a": "talk", "anim_b": "talk",
                    "llm_prompt": (f"Two minions in the {sci} guild: A ({{name_a}}, {mood}) "
                                   f"{verb} B ({{name_b}}). Write their exchange — 2 short "
                                   f"lines of dialogue, true to their bond and the science."),
                }


def gen_stories() -> Iterable[dict]:
    """The MILLIONS: archetype × science × sub-niche × emotion × era × beat. Each a
    distinct story scaffold with an LLM prompt that Llama fills with the real cast."""
    for arch, beats in ARCHETYPES.items():
        for sci in SCIENCES:
            niches = _sub_niches(sci)
            for niche in niches:
                for mood in MOODS:
                    for ei, era in enumerate(ERAS):
                        for act, beat in enumerate(beats):
                            sid = _h(arch, sci, niche, mood, era, act)
                            yield {
                                "story_id": f"st-{sid:010x}",
                                "archetype": arch, "act": act, "beat": beat,
                                "science": sci, "sub_niche": niche,
                                "emotion": mood, "era": era,
                                "cast_roles": "hero,mentor,rival",
                                "mood_from": mood,
                                "mood_to": _pick(_h(sid, "to"), MOODS),
                                "learning_benefit": round(0.5 + (sid % 30) / 10.0, 2),
                                "rarity": _pick(_h(sid, "r"), ["common", "common", "uncommon", "rare", "legendary"]),
                                "llm_prompt": (
                                    f"Continue the saga '{arch}' at the beat '{beat}'. "
                                    f"{{hero}} of the {{guild}} guild pursues {sci}/{niche} "
                                    f"in the {era} era, feeling {mood}. Write this beat as "
                                    f"2-3 grounded, emotional sentences naming their real "
                                    f"discovery and the minions involved."),
                            }


# ── CSV writer (streamed; optional cap) ─────────────────────────────────────────────
def _write(path: str, rows: Iterable[dict], cap: Optional[int]) -> int:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    n, fields, f, w = 0, None, None, None
    for r in rows:
        if w is None:
            fields = list(r.keys())
            f = open(path, "w", newline="", encoding="utf-8")
            w = csv.DictWriter(f, fieldnames=fields)
            w.writeheader()
        w.writerow(r)
        n += 1
        if cap and n >= cap:
            break
    if f:
        f.close()
    return n


def generate(out_dir: str, *, stories_cap: Optional[int] = 3_000_000) -> dict:
    counts = {}
    counts["sciences.csv"] = _write(os.path.join(out_dir, "sciences.csv"), gen_sciences(), None)
    counts["emotions.csv"] = _write(os.path.join(out_dir, "emotions.csv"), gen_emotions(), None)
    counts["interactions.csv"] = _write(os.path.join(out_dir, "interactions.csv"), gen_interactions(), None)
    counts["stories.csv"] = _write(os.path.join(out_dir, "stories.csv"), gen_stories(), stories_cap)
    subjects = sum(len(_sub_niches(s)) for s in SCIENCES)             # ~5,000 real subjects
    beats = sum(len(b) for b in ARCHETYPES.values())                  # total beats
    full_stories = subjects * len(MOODS) * len(ERAS) * beats          # the full space
    return {"out_dir": out_dir, "counts": counts,
            "subjects_real": subjects,
            "stories_full_combinations": full_stories,
            "stories_written": counts["stories.csv"],
            "stories_capped": bool(stories_cap and counts["stories.csv"] >= stories_cap),
            "sciences": len(SCIENCES), "archetypes": len(ARCHETYPES),
            "moods": len(MOODS), "feelings": len(FEELINGS), "eras": len(ERAS)}


if __name__ == "__main__":
    import json
    import sys
    out = sys.argv[1] if len(sys.argv) > 1 else "data/design"
    cap = int(sys.argv[2]) if len(sys.argv) > 2 else None
    print(json.dumps(generate(out, stories_cap=cap), indent=2))
