#!/usr/bin/env python3
"""Image-first GLB generation — Harmony Heights quality.

The right Tripo pipeline (proven): text -> Nano Banana Pro IMAGE (which understands the
Avatar x Sims4 x GTA5 theme) -> image_to_model with FULL PBR + HD + smart-mesh-v2 + ~20k
faces. image_to_model reconstructs the full 3D (internal multiview) from the themed image,
so each GLB looks like the reference render, not a generic text-to-3D blob. Saves the Nano
Banana preview .png next to each .glb for instant QA.

Resumable (skips existing), budget-capped, concurrency-limited, stops cleanly on 403/credit.
  export TRIPO_API_KEY=...
  python3 scripts/tripo_imagefirst.py --budget-credits 300000 --concurrency 4
"""
from __future__ import annotations
import argparse, json, os, sys, time, urllib.request, urllib.error, uuid, threading
from concurrent.futures import ThreadPoolExecutor, as_completed

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPECS = os.path.join(ROOT, "data", "master", "gen_specs.jsonl")
API = os.environ.get("TRIPO_BASE", "https://api.tripo3d.ai/v2/openapi")
KEY = os.environ.get("TRIPO_API_KEY", "")
IMAGE_MODEL = os.environ.get("UW_IMAGE_MODEL", "gpt4o")
# GPT Image 2 via OpenAI directly (Tripo's API can't pick the image model). When set, the
# themed image is generated by OpenAI's image model, then fed to Tripo image-to-3D.
OPENAI_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_IMAGE_MODEL = os.environ.get("UW_OPENAI_IMAGE_MODEL", "gpt-image-1")
CR_IMG, CR_MODEL = 10, 30  # approx Tripo credits for accounting

# The operator's phrasing: "a futuristic single GLB asset of a futuristic <thing> created for an
# Avatar-movie x GTA 5 x The Sims 4 world" + per-domain visual cues + single-isolated-on-white
# (which is what image-to-3D needs).
WORLD = ("created for a world where Avatar the movie is mixed with Grand Theft Auto 5 and The Sims 4 — "
         "sleek white and glass sci-fi forms, glowing cyan and violet neon and holographic accents, "
         "clean stylized yet realistic, modern, highly detailed")
FRAME = {
    "building": ("a futuristic single 3D asset of a futuristic {name} building, {world}, curved white "
                 "architecture, glass balconies, neon plumbob signage, holographic billboard, rooftop garden, "
                 "purple jacaranda trees, single isolated building, isometric view, plain white background"),
    "vehicle": ("a futuristic single 3D asset of a futuristic {name}, {world}, Tron-style aerodynamic body, "
                "glowing neon light strips, sci-fi wheels, bioluminescent underglow, single isolated vehicle, "
                "studio product shot, three-quarter front view, plain white background"),
    "character": ("a futuristic single 3D asset of a futuristic {name} game character, {world}, full body, "
                  "sleek sci-fi outfit with glowing accents, neutral A-pose, single isolated character, "
                  "front view, plain white background"),
    "nature": ("a futuristic single 3D asset of a {name}, {world}, with bioluminescent glow, single isolated "
               "natural object, plain white background"),
    "sky": ("a single 3D asset of a {name}, {world}, luminous glowing celestial element, plain black background"),
    "urban": ("a futuristic single 3D asset of a futuristic {name}, {world}, modern city street object with "
              "neon accents, single isolated object, studio product shot, plain white background"),
    "interior": ("a futuristic single 3D asset of a futuristic {name}, {world}, sleek object with glowing neon "
                 "accents and holographic details, single isolated object, studio product shot, plain white background"),
}


def _req(method, url, body=None, raw=False, timeout=180, retries=5):
    data = json.dumps(body).encode() if body is not None else None
    delay = 2.0
    for a in range(retries):
        r = urllib.request.Request(url, data=data, method=method)
        if KEY: r.add_header("Authorization", f"Bearer {KEY}")
        if data is not None: r.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(r, timeout=timeout) as resp:
                return resp.read() if raw else json.loads(resp.read().decode())
        except urllib.error.HTTPError as e:
            if e.code in (429, 500, 502, 503, 504) and a < retries - 1:
                time.sleep(delay); delay = min(delay * 2, 30); continue
            raise
        except urllib.error.URLError:
            if a < retries - 1:
                time.sleep(delay); delay = min(delay * 2, 30); continue
            raise


def _poll(tid, timeout=600, every=4):
    s = time.time()
    while time.time() - s < timeout:
        d = _req("GET", f"{API}/task/{tid}")["data"]
        st = d.get("status")
        if st == "success": return d.get("output") or {}
        if st in ("failed", "cancelled", "error", "expired", "banned"):
            raise RuntimeError(f"task {st}: {d.get('message','')}")
        time.sleep(every)
    raise TimeoutError("poll timeout")


def _upload(jpg_bytes):
    bnd = "----t" + uuid.uuid4().hex
    body = (f'--{bnd}\r\nContent-Disposition: form-data; name="file"; filename="img.jpg"\r\n'
            f'Content-Type: image/jpeg\r\n\r\n').encode() + jpg_bytes + f'\r\n--{bnd}--\r\n'.encode()
    r = urllib.request.Request(f"{API}/upload", data=body, method="POST")
    r.add_header("Authorization", f"Bearer {KEY}")
    r.add_header("Content-Type", f"multipart/form-data; boundary={bnd}")
    with urllib.request.urlopen(r, timeout=120) as x:
        return json.loads(x.read().decode())["data"]["image_token"]


# Only spend the expensive image-first pipeline on assets that MATTER as big renders.
# Skip trivial small props (cutlery, tiny decor) — they don't need hero quality.
TRIVIAL = (
    "fork", "spoon", "knife", "teaspoon", "tablespoon", "plate", "saucer", "bowl", "cup", "mug",
    "glass", "tumbler", "flute", "napkin", "ramekin", "ladle", "spatula", "whisk", "tongs",
    "peeler", "grater", "sieve", "colander", "cutlery", "chopstick", "straw", "coaster",
    "candle", "candlestick", "vase", "picture frame", "photo frame", "ornament", "trinket",
    "doily", "placemat", "salt", "pepper", "sugar bowl", "creamer", "trivet", "oven mitt",
    "tea towel", "dish cloth", "sponge", "soap", "toothbrush", "comb", "pencil", "pen",
    "paperclip", "stapler", "eraser", "sticky note", "magnet", "key", "coin", "button",
    "bookmark", "envelope", "stamp", "ashtray", "lighter", "matchbox", "clothespin",
)
HERO_DOMAINS = {"building", "vehicle", "character", "sky"}
HERO_KW = ("machine", "rig", "station", "bench", "console", "reactor", "furnace", "scanner",
           "microscope", "lathe", "mill", "drill", "press", "turbine", "robot", "telescope",
           "chamber", "spectrometer", "centrifuge", "workstation", "terminal", "workbench",
           "anvil", "forge", "conveyor", "exosuit", "incubator", "bed", "sofa", "couch", "desk",
           "table", "wardrobe", "dresser", "cabinet", "bookshelf", "shelf", "counter", "fridge",
           "refrigerator", "oven", "stove", "fountain", "statue", "monument", "tree", "rock",
           "cliff", "mountain", "waterfall", "tower", "wall", "facade", "roof", "stair", "bridge",
           "gate", "altar", "throne", "piano", "fireplace", "tv", "treadmill", "operating",
           "hospital bed", "drone", "boat", "ship", "plane", "train", "tram", "loom", "kiln")


def matters(spec):
    name = spec["name"].lower()
    if spec["domain"] in HERO_DOMAINS:
        return True
    if any(t in name for t in TRIVIAL):
        return False
    if any(k in name for k in HERO_KW):
        return True
    # default: skip small unspecified interior bits, keep larger civic/urban/nature things
    return spec["domain"] in ("urban", "nature")


def image_prompt(spec):
    dom = spec["domain"]
    tmpl = FRAME.get(dom, FRAME["interior"])
    return tmpl.format(name=spec["name"], world=WORLD)


def _openai_image(prompt, retries=12):
    """Generate a themed image with OpenAI (GPT Image 2). Returns PNG bytes. gpt-image-2 throws
    frequent transient 520s under load — retry patiently with backoff + jitter."""
    import base64, random
    body = {"model": OPENAI_IMAGE_MODEL, "prompt": prompt, "size": "1024x1024", "n": 1}
    delay = 4.0
    for a in range(retries):
        r = urllib.request.Request("https://api.openai.com/v1/images/generations",
                                   data=json.dumps(body).encode(), method="POST")
        r.add_header("Authorization", f"Bearer {OPENAI_KEY}")
        r.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(r, timeout=300) as x:
                d = json.loads(x.read().decode())["data"][0]
            return base64.b64decode(d["b64_json"]) if d.get("b64_json") else _req("GET", d["url"], raw=True, timeout=120)
        except urllib.error.HTTPError as e:
            if e.code in (429, 500, 502, 503, 504, 520, 522, 524) and a < retries - 1:
                time.sleep(delay + random.uniform(0, 3)); delay = min(delay * 1.7, 45); continue
            raise
        except urllib.error.URLError:
            if a < retries - 1:
                time.sleep(delay); delay = min(delay * 1.7, 45); continue
            raise


def make_image(spec):
    """Just the themed image (GPT Image 2 via OpenAI, or Tripo default). Saves the preview, returns its path."""
    dest = os.path.join(ROOT, spec["out_glb"])
    prev = dest.rsplit(".", 1)[0] + ".preview.png"
    if OPENAI_KEY:
        img = _openai_image(image_prompt(spec))       # GPT Image 2 directly
    else:
        tid = _req("POST", f"{API}/task",
                   {"type": "text_to_image", "prompt": image_prompt(spec), "image_model": IMAGE_MODEL}
                   )["data"]["task_id"]
        img_url = _poll(tid).get("generated_image")
        if not img_url: raise RuntimeError("no image")
        img = _req("GET", img_url, raw=True, timeout=120)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(prev, "wb").write(img)
    return prev


def convert_one(spec):
    """Convert an ALREADY-MADE preview image -> Tripo image_to_model GLB (full PBR/HD/20k).
    Reuses the existing .preview.png (no OpenAI re-cost). Caller ensures it exists + glb missing."""
    dest = os.path.join(ROOT, spec["out_glb"])
    prev = dest.rsplit(".", 1)[0] + ".preview.png"
    img = open(prev, "rb").read()
    tok = _upload(img)
    body = {"type": "image_to_model", "file": {"type": "jpeg", "file_token": tok},
            "model_version": "v2.5-20250123", "texture": True, "pbr": True,
            "texture_quality": "detailed", "face_limit": 20000, "quad": True, "auto_size": True}
    tid2 = _req("POST", f"{API}/task", body)["data"]["task_id"]
    out = _poll(tid2, timeout=700)
    murl = out.get("pbr_model") or out.get("model")
    if isinstance(murl, dict): murl = murl.get("url")
    if not murl: raise RuntimeError(f"no model url: {list(out)}")
    glb = _req("GET", murl, raw=True, timeout=400)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(dest, "wb").write(glb)
    return len(glb)


def generate_one(spec):
    """themed image (GPT Image 2 via OpenAI, or Tripo default) -> Tripo image_to_model (full PBR/HD/20k)."""
    make_image(spec)                                   # save preview for QA
    return convert_one(spec)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--budget-credits", type=int, default=300000)
    ap.add_argument("--concurrency", type=int, default=4)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--images-only", action="store_true",
                    help="smash out ALL the GPT-Image-2 images first (no 3D); fast, OpenAI-only cost")
    ap.add_argument("--convert-ready", action="store_true",
                    help="convert ALREADY-MADE preview images -> GLBs (reuses previews; Tripo cost). "
                         "Pair with --watch to pick up images as the --images-only batch produces them.")
    ap.add_argument("--watch", action="store_true", help="keep scanning for newly-made previews")
    ap.add_argument("--watch-interval", type=int, default=30, help="seconds between watch scans")
    ap.add_argument("--watch-max-idle", type=int, default=40, help="give up after N idle scans")
    a = ap.parse_args()
    if not KEY and not a.images_only:
        print("set TRIPO_API_KEY"); sys.exit(2)
    specs = [json.loads(l) for l in open(SPECS)]
    if a.limit: specs = specs[:a.limit]
    specs = [s for s in specs if matters(s)]          # only the things that matter as big renders
    DOM_ORDER = {"building": 0, "vehicle": 1, "character": 2, "urban": 3, "sky": 4,
                 "nature": 5, "interior": 6, "era": 7}

    if a.convert_ready:
        # Convert previews -> GLBs N-at-a-time, optionally watching for new ones (runs alongside
        # the --images-only batch). Hero domains first. Stops cleanly on Tripo credit exhaustion.
        print(f"CONVERT-READY: image->GLB, {a.concurrency} at a time, watch={a.watch} "
              f"(full PBR+HD+smartmesh-v2+20k)", flush=True)
        lock = threading.Lock(); st = {"ok": 0, "fail": 0, "spent": 0, "stop": False}
        seen: set[str] = set()

        def _ready():
            out = []
            for s in specs:
                dest = os.path.join(ROOT, s["out_glb"])
                if dest in seen or os.path.exists(dest):
                    continue
                if os.path.exists(dest.rsplit(".", 1)[0] + ".preview.png"):
                    out.append(s)
            out.sort(key=lambda s: (DOM_ORDER.get(s["domain"], 9), s.get("priority", 9)))
            return out

        def cwork(s):
            if st["stop"]: return
            dest = os.path.join(ROOT, s["out_glb"])
            with lock:
                if st["spent"] + CR_MODEL > a.budget_credits: st["stop"] = True; return
                if dest in seen: return
                seen.add(dest); st["spent"] += CR_MODEL
            try:
                n = convert_one(s)
                with lock:
                    st["ok"] += 1
                    print(f"  [{st['ok']}] GLB {s['name'][:34]:34s} {n//1024}KB ~{st['spent']}cr", flush=True)
            except Exception as e:
                with lock:
                    st["fail"] += 1; st["spent"] -= CR_MODEL
                    msg = str(e)[:140]
                    print(f"  FAIL {s['name'][:30]}: {msg}", flush=True)
                    if any(k in msg.lower() for k in ("credit", "balance", "402", "403", "forbidden", "insufficient")):
                        st["stop"] = True; print("  -> out of credits; stopping.", flush=True)

        idle = 0
        while not st["stop"]:
            batch = _ready()
            if not batch:
                if not a.watch: break
                idle += 1
                if idle >= a.watch_max_idle:
                    print(f"  no new images for {idle} scans; done.", flush=True); break
                time.sleep(a.watch_interval); continue
            idle = 0
            with ThreadPoolExecutor(max_workers=a.concurrency) as ex:
                futs = [ex.submit(cwork, s) for s in batch]
                for _ in as_completed(futs):
                    if st["stop"]: break
            if not a.watch: break
            time.sleep(2)
        print(f"\nconvert-ready done: {st['ok']} GLBs, {st['fail']} failed, ~{st['spent']} credits.", flush=True)
        return

    if a.images_only:
        # Phase 1: generate ALL hero images (GPT Image 2) in one go; skip 3D.
        todo = [s for s in specs
                if not os.path.exists(os.path.join(ROOT, s["out_glb"]).rsplit(".", 1)[0] + ".preview.png")]
        todo.sort(key=lambda s: (DOM_ORDER.get(s["domain"], 9), s.get("priority", 9)))
        print(f"IMAGES-ONLY (GPT Image 2): {len(specs)} hero assets, {len(todo)} images to make", flush=True)
        lock = threading.Lock(); st = {"ok": 0, "fail": 0}
        def imgwork(s):
            try:
                make_image(s)
                with lock:
                    st["ok"] += 1
                    if st["ok"] % 5 == 0 or st["ok"] < 6:
                        print(f"  [{st['ok']}/{len(todo)}] img: {s['name'][:40]}", flush=True)
            except Exception as e:
                with lock:
                    st["fail"] += 1; print(f"  FAIL img {s['name'][:30]}: {str(e)[:120]}", flush=True)
        with ThreadPoolExecutor(max_workers=a.concurrency) as ex:
            list(as_completed([ex.submit(imgwork, s) for s in todo]))
        print(f"\ndone images: {st['ok']} made, {st['fail']} failed. Next: run without --images-only for the GLBs.", flush=True)
        return

    todo = [s for s in specs if not os.path.exists(os.path.join(ROOT, s["out_glb"]))]
    todo.sort(key=lambda s: (DOM_ORDER.get(s["domain"], 9), s.get("priority", 9)))
    print(f"(image-first only on assets that matter: {len(specs)} qualify, {len(todo)} not yet made)", flush=True)
    per = CR_IMG + CR_MODEL
    print(f"image-first | specs={len(specs)} done={len(specs)-len(todo)} to-generate={len(todo)} "
          f"| ~{len(todo)*per:,} credits | model={IMAGE_MODEL} | full PBR+HD+smartmesh-v2+20k", flush=True)

    lock = threading.Lock(); st = {"ok": 0, "fail": 0, "spent": 0, "stop": False}

    def work(s):
        if st["stop"]: return
        with lock:
            if st["spent"] + per > a.budget_credits: st["stop"] = True; return
            st["spent"] += per
        try:
            n = generate_one(s)
            with lock:
                st["ok"] += 1
                print(f"  [{st['ok']}/{len(todo)}] {s['name'][:34]:34s} {n//1024}KB ~{st['spent']}cr", flush=True)
        except Exception as e:
            with lock:
                st["fail"] += 1; st["spent"] -= per
                msg = str(e)[:140]
                print(f"  FAIL {s['name'][:30]}: {msg}", flush=True)
                if any(k in msg.lower() for k in ("credit", "balance", "402", "403", "forbidden", "insufficient")):
                    st["stop"] = True; print("  -> out of credits; stopping.", flush=True)

    with ThreadPoolExecutor(max_workers=a.concurrency) as ex:
        futs = [ex.submit(work, s) for s in todo]
        for _ in as_completed(futs):
            if st["stop"]: break
    print(f"\ndone: {st['ok']} generated, {st['fail']} failed, ~{st['spent']} credits. Re-run to continue.", flush=True)


if __name__ == "__main__":
    main()
