#!/usr/bin/env python3
"""Generate the Overnight Panels registry from the self-contained cinematic panel components.

The overnight loop produced ~110 self-contained, zero-prop React panels under
src/components/cinematic/ that were never wired into the app. Rather than mounting 110 floating
toggle buttons globally (collision + clutter), we expose them through ONE launcher overlay that
lazy-mounts a chosen panel. This script scans those components and emits a metadata registry the
launcher consumes (via vite's import.meta.glob). Re-run it whenever new panels land.

A component qualifies as a launchable panel when:
  - it lives in src/components/cinematic/ and has `export default`
  - it is NOT already wired into src/App.jsx or src/Layout.jsx (those are live already)
  - it is NOT a command-palette / global-keyboard component (would hijack the live palette / keys)

Output: src/components/overnight/panelRegistry.generated.js  (export const PANELS = [...])
Usage:  python3 scripts/gen_panel_registry.py
"""
from __future__ import annotations

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CINEMATIC = os.path.join(ROOT, "src", "components", "cinematic")
OUT = os.path.join(ROOT, "src", "components", "overnight", "panelRegistry.generated.js")

# Components that must NOT be launchable panels: command palettes (hijack ⌘K) and global key/nav hijackers.
EXCLUDE_RE = re.compile(r"(Palette|ShowMeNavigation|SceneKeyboardNav|HeyJarvisListener)", re.I)

# Category assignment — first matching keyword wins; order matters (specific before generic).
CATEGORY_RULES = [
    ("Threat & Intel", ("Threat", "Intel", "Crisis", "GeoSeismic", "AdaptiveThreat", "WorldRisk", "WorldIncident")),
    ("Graph", ("Graph",)),
    ("Risk", ("Risk",)),
    ("Investigations", ("Investigation", "Scenario")),
    ("Datasets & Knowledge", ("Dataset", "Knowledge", "Document", "Report")),
    ("Finance", ("Investment", "Market", "Portfolio", "Wealth")),
    ("Skills", ("Skill",)),
    ("Contacts & Entities", ("Contact", "Entity", "Task")),
    ("Swarm", ("Swarm",)),
    ("Scenes", ("Scene",)),
    ("Operations", ("Ops", "Situation", "Service", "Resource", "Priority", "Daily", "Morning",
                    "Alert", "System", "Mission", "Runbook", "Telemetry", "Diagnostic")),
]


def wired_names() -> set[str]:
    """Component basenames already imported by the live shell (App.jsx / Layout.jsx) — skip these."""
    names = set()
    for rel in ("src/App.jsx", "src/Layout.jsx"):
        p = os.path.join(ROOT, rel)
        if os.path.exists(p):
            txt = open(p, encoding="utf-8").read()
            names |= set(re.findall(
                r"import\s+[A-Za-z0-9_]+\s+from\s+['\"][^'\"]*?/([A-Za-z0-9_]+)['\"]", txt))
    return names


def categorize(name: str) -> str:
    for cat, kws in CATEGORY_RULES:
        if any(k.lower() in name.lower() for k in kws):
            return cat
    return "Other"


def labelize(name: str) -> str:
    """CamelCase component name -> human label (e.g. SituationRoom -> 'Situation Room')."""
    return re.sub(r"(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", " ", name).strip()


def extract_endpoints(src: str) -> list[str]:
    eps = re.findall(r"/(?:v1|entities|knowledge)/[A-Za-z0-9/_-]+", src)
    seen, out = set(), []
    for e in eps:
        e = e.rstrip("/`'\"")
        if e not in seen:
            seen.add(e)
            out.append(e)
    return out[:6]


def main() -> int:
    wired = wired_names()
    panels = []
    for fn in sorted(os.listdir(CINEMATIC)):
        if not fn.endswith(".jsx"):
            continue
        name = fn[:-4]
        if name in wired or EXCLUDE_RE.search(name):
            continue
        src = open(os.path.join(CINEMATIC, fn), encoding="utf-8").read()
        if "export default" not in src:
            continue
        panels.append({
            "key": name,
            "label": labelize(name),
            "category": categorize(name),
            "file": fn,
            "endpoints": extract_endpoints(src),
        })

    panels.sort(key=lambda p: (p["category"], p["label"]))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    header = ("// AUTO-GENERATED by scripts/gen_panel_registry.py — do not edit by hand.\n"
              "// The Overnight Panels launcher (OvernightPanels.jsx) consumes this list and lazy-mounts\n"
              "// each panel via import.meta.glob('../cinematic/*.jsx'). Re-run the generator to refresh.\n")
    body = "export const PANELS = " + json.dumps(panels, indent=2, ensure_ascii=False) + ";\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header + body)

    cats = {}
    for p in panels:
        cats[p["category"]] = cats.get(p["category"], 0) + 1
    print(f"wrote {len(panels)} panels -> {os.path.relpath(OUT, ROOT)}")
    for c, n in sorted(cats.items()):
        print(f"  {c}: {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
